accounts/urls.py
# -*- coding: utf-8 -*-

""" Shop url configuration"""
from django.urls import path
from django.contrib.auth import views as auth_views
from django.utils.translation import gettext_lazy as _

from accounts import views as accounts_views


app_name = 'accounts'

urlpatterns = (
    path(_('account/register/'), accounts_views.register_request, name='register'),
    path(_('account/profile/'), accounts_views.profile, name='profile'),
    path(_('account/login/'), accounts_views.login_request, name='login'),
    path(_('account/logout/'), auth_views.LogoutView.as_view(
        template_name="shop/produit/shop_listing.html"), name='logout'),
)

ecommerce/urls.py
# -*- coding: utf-8 -*-

"""
    ecommerce URL Configuration
"""

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

admin.autodiscover()

if 'rosetta' in settings.INSTALLED_APPS:
     urlpatterns = i18n_patterns(
          # path('__debug__/', include(debug_toolbar.urls)),
          path(_('admin/'), admin.site.urls),
          path(_('admin/doc/'), include('django.contrib.admindocs.urls')),
          path('', include('accounts.urls', namespace='accounts')),
          path(_('cart/'), include('panier.urls', namespace='panier')),
          path(_('orders/'), include('commandes.urls', namespace='commandes')),
          path(_('payment/'), include('payment.urls', namespace='payment')),
          path(_('coupons/'), include('coupons.urls', namespace='coupons')),
          path('rosetta/', include('rosetta.urls')),
          path('tinymce/', include('tinymce.urls')),
          path('', include('shop.urls', namespace='shop')),
    )

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panier/urls.py
# -*- coding: utf-8 -*-

"""
    Panier URL configuration
"""

from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views as views

app_name = 'panier'

urlpatterns = [
    path('', views.detail_panier, name="detail_panier"),
    path(_('panier/add/<int:id_produit>/'), views.ajout_panier, name="ajout_panier"),
    path(_('panier/remove/<int:id_produit>/'), views.enlever_panier, name="enlever_panier"),
]

shop/urls.py
# -*- coding: utf-8 -*-


from django.urls import path
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import gettext_lazy as _

from . import views
from marketing.views import email_list_signup
from shop.sitemaps import CatSitemaps


sitemaps = {
    'cat': CatSitemaps,
}

app_name = 'shop'

urlpatterns = (
    # ex: /
    path('', views.all_produit, name='all_produit'),
    # ex: subscribe/
    path(_('subscribe/'), email_list_signup, name='marketing'),

    # ex: search/
    path(_('search/'), views.search, name='search'),

    # ex: shop/product/
    path(_('shop/product/<slug:slug>/<int:id>/'), views.detail_produit, name='detail_produit'),

    # ex: shop/marque/
    path(_('shop/marque/'), views.all_marques, name='all_marque'),
    path(_('shop/marque/<slug:marque_slug>/'), views.liste_marques, name='listing_marques'),

    # ex: shop/category/
    path(_('shop/category/'), views.all_categorie, name='all_categorie'),
    path(_('shop/category/<slug:category_slug>/'), views.liste_categorie, name='listing_categorie'),
    path(_('shop/category/<slug:category_slug>/'), views.all_produit, name='all_produit'),

    # ex: shop/review/
    path(_('shop/review/'), views.review_list, name='review_list'),
    path(_('shop/review/<slug:review_id>/'), views.review_detail, name='review_detail'),
    path(_('shop/add_review/<int:produit_id>/'), views.add_review, name='add_review'),

    # ex: shop/profile/
    path('shop/profile/<slug:username>/', views.user_review_list, name='user_review_list'),
    path('shop/profile/', views.user_review_list, name='user_review_list'),

    # ex: shop/recommendation/ - get wine recommendations for the logged user
    path('shop/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

templates/_includes/csslink.html
        {% load static %}

        <!--[if IE 7]><html class="ie ie7"><![endif]-->
        <!--[if IE 8]><html class="ie ie8"><![endif]-->
        <!--[if IE 9]><html class="ie ie9"><![endif]-->

        <meta charset="utf-8">
        <meta http-equiv='content-language' content='fr'>
        <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8; X-Content-Type-Options=nosniff">
        {% if page_title %}<meta name="title" content="{{ page_title }}">{% else %}<meta name="title" content="{{ site_name }}">{% endif %}

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="format-detection" content="telephone=no">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="google" content="nositelinkssearchbox">

        <meta name="keywords" content="{{ meta_keywords }}">
        <meta name="description" content="{{ meta_description }}">
        <meta name="robots" content="noindex,follow">
        <meta rel="canonical" href="{% url "shop:all_produit" %}{{ site_name }}">

        <meta name="author" content="">
        <meta name="twitter:card" content="">
        <meta name="twitter:site" content="">
        <meta name="twitter:title" content="">
        <!-- ./meta -->

            <!-- plugins: icons -->
            <link href="{% static "fontawesome/css/all.css" %}" rel="stylesheet">
            <link href="{% static "lineicon/css/simple-line-icons.css" %}" rel="stylesheet">

            <!-- Bootstrap4 files-->
            <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
            <link href="{% static "css/bootstrap.min.css.map" %}" rel="stylesheet">
            <link href="{% static "css/responsive.css" %}" rel="stylesheet" media="only screen and (max-width: 1200px)">

            <!-- Material Design Bootstrap -->
            <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">

            <!-- plugin : ps-icon -->
            <link rel="stylesheet" type="text/css" href="{% static "psicon/style.css" %}">

            <!-- plugin : owlcarousel -->
            <link href="{% static "owl/owl.carousel.min.css" %}" rel="stylesheet">

            <!-- plugin : slickslider -->
            <link href="{% static "slick/slick.css" %}" rel="stylesheet">
            <link href="{% static "slick/slick-theme.css" %}" rel="stylesheet">

            <!-- plugin: fancybox  -->
            <link href="{% static "fancybox/fancybox.min.css" %}" type="text/css" rel="stylesheet">

            <!-- custom style -->
            <link href="{% static "css/style.css" %}" rel="stylesheet">

            <style>
                @media (max-width: 740px) {
                    html, body, header{ height: 100vh; }
                }

                @media (min-width: 800px) and (max-width: 850px) {
                    html, body, header{ height: 100vh; }
                }
            </style>
        <!--[if IE 7]><body class="ie7 lt-ie8 lt-ie9 lt-ie10"><![endif]-->
        <!--[if IE 8]><body class="ie8 lt-ie9 lt-ie10"><![endif]-->
        <!--[if IE 9]><body class="ie9 lt-ie10"><![endif]-->

templates/_includes/footer.html
  {% load i18n static %}

    <style>
      .footer {
        background: #e0e0e0;
      }
      .copyright {
        background: #333;
        color: #ccc;
      }

      #button-addon1 {
        color: #ffc371;
      }

      .form-control::placeholder {
        font-size: 0.95rem;
        color: #aaa;
        font-style: italic;
      }
    </style>



    <!-- Footer -->
    <footer class="footer flex-shrink-0">
      <div class="container p-5">
        <div class="row">
          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
            <a href="{% url "shop:all_produit" %}" class="stretched-link">
              <img src="{% static "img/logo.png" %}" alt="" class="w-25 d-block img-fluid mb-3">
            </a>
            <p class="font-italic text-muted small">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
            </p>
            <ul class="list-inline mt-4">
              <li class="list-inline-item"><a href="#" target="_blank" title="twitter">
                <i class="fab fa-twitter-square"></i></a>
              </li>

              <li class="list-inline-item">
                <a href="#" target="_blank" title="facebook"><i class="fab fa-facebook-f"></i></a>
              </li>

              <li class="list-inline-item">
                <a href="#" target="_blank" title="instagram"><i class="fab fa-instagram"></i></a>
              </li>
            </ul>
          </div><!-- ./logo -->

          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4">Shop</h6>
            <ul class="list-unstyled mb-0">
              <li class="mb-2"><a href="#" class="text-muted">Stores</a></li>
            </ul>
          </div><!-- ./shopping -->

          <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4">Company</h6>
            <ul class="list-unstyled mb-0">
              <li class="mb-2"><a href="#" class="text-muted">Wishlist</a></li>
              <li class="mb-2"><a href="#" class="text-muted">Our Products</a></li>
            </ul>
          </div><!-- ./company -->


          <div class="col-lg-3 col-md-6 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4">{% trans "Newsletter" %}</h6>
            <p class="text-muted mb-4">
              {% trans "Subscribe to our communications to receive our best offers !" %}
            </p>
            <div class="rounded border">
              <form class="input-group" action="{% url "shop:marketing" %}" method="POST">
                {% csrf_token %}
                <input id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" type="{{ form.email.label }}" placeholder="{% trans "Enter your email address" %}" aria-describedby="button-addon" class="form-control border shadow-none" required>
                <div class="input-group-append">
                  <button id="button-addon" type="submit" class="input-group-text">
                    <i class="fa fa-paper-plane"></i>
                  </button>
                </div>
              </form>
            </div>
          </div><!-- ./subscribe -->
        </div>
      </div>

      <!-- Copyrights -->
      <div class="copyright py-4">
        <div class="container text-center">
          <p class="text-muted mb-0 py-2">© <script>document.write(new Date().getFullYear());</script> All rights reserved.</p>
        </div>
      </div>
    </footer>
  <!-- End -->

templates/_includes/jscripts.html
        {% load static %}

        <!-- JQuery tooltips -->

            <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
            <!-- Bootstrap4 files-->
            <script type="text/javascript" src="{% static "js/popper.min.js" %}" ></script>
            <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
            <!-- MDB core JavaScript -->
            <script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
            <!-- plugin: owl carousel  -->
            <script type="text/javascript" src="{% static "owl/owl.carousel.min.js" %}"></script>
            <!-- plugin: slickslider  -->
            <script type="text/javascript" src="{% static "slick/slick.min.js" %}"></script>
            <!-- plugin: fancybox  -->
            <script type="text/javascript" src="{% static "fancybox/fancybox.min.js" %}"></script>
            <!-- custom js -->
            <script type="text/javascript" src="{% static "js/main.js" %}"></script>

templates/_includes/navbar.html
            {% load i18n static %}
            <!-- lang-->
            <div id="topbar lang" class="p-1">
                <div class="container">
                    <div class="row d-flex align-items-center">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        <div class="col-lg-12 text-center">
                            <ul class="menu list-inline mb-0">
                                {% for language in languages %}
                                    <li class="list-inline-item {% if language.code == LANGUAGE_CODE %} active {% endif %}">
                                        <a href="/{{ language.code }}{{ next }}" class="font-weight-normal">
                                            {{ language.name_local }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./lang-->

            <!-- topbar-->
            <div id="lang">
                <div class="container">
                    <div class="row d-flex align-items-center text-center">
                        <div class="col-12">
                            <!-- section service content -->
                            <div class="btn btn-sm shadow-none icon d-inline-flex align-items-center text-left">
                                <div class="text-center icon-wrap icon-sm rounded-circle border-success border text-success d-inline-block position-relative">
                                    <i class="ps-icon-customer-service"></i>
                                </div>

                                <div class="text-wrap d-none d-md-inline-block">
                                    <div class="font-weight-bolder">{% trans "Call us" %}</div>
                                    <small class="d-block">00 000 000 / 00 000 000</small>
                                </div>
                            </div>

                            <div class="btn btn-sm shadow-none icon d-inline-flex align-items-center text-left">
                                <div class="text-center icon-wrap icon-sm rounded-circle border-success border text-success d-inline-block position-relative">
                                    <i class="ps-icon-delivery"></i>
                                </div>

                                <div class="text-wrap d-none d-md-inline-block">
                                    <div class="font-weight-bolder">{% trans "Free delivery" %}</div>
                                    <small class="d-block">{% trans "in less than 24H" %}</small>
                                </div>
                            </div>

                            <div class="btn btn-sm shadow-none icon d-inline-flex align-items-center text-left">
                                <div class="text-center icon-wrap icon-sm rounded-circle border-success border text-success d-inline-block position-relative">
                                    <i class="icon-clock"></i>
                                </div>

                                <div class="text-wrap d-none d-md-inline-block">
                                    <div class="font-weight-bolder">{% trans "Availability" %}</div>
                                    <small class="d-block">{% trans "7 days/7" %}</small>
                                </div>
                            </div>

                            <div class="btn btn-sm shadow-none icon d-inline-flex align-items-center text-left">
                                <div class="text-center icon-wrap icon-sm rounded-circle border-success border text-success d-inline-block position-relative">
                                    <i class="icon-credit-card"></i>
                                </div>

                                <div class="text-wrap d-none d-md-inline-block">
                                    <div class="font-weight-bolder">{% trans "Payment" %}</div>
                                    <small class="d-block">{% trans "in complete security" %}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--./topbar-->

            <!-- topbar-->
            <div id="topbar" class="p-1">
                <div class="container">
                    <div class="row d-flex align-items-center">
                        <div class="col-lg-6 text-center offer mb-2 mb-lg-0 text-white">
                            <a href="#" class="btn btn-success btn-sm text-white">Offer of the day</a>
                            <a href="#" class="ml-1 text-white">Get flat 35% off on orders over $50!</a>
                        </div>

                        <div class="col-lg-6 text-center offer mb-lg-0">
                            <div class="d-flex justify-content-end justify-content-between pt-3">
                                {% if user.is_authenticated %}
                                    <ul class="list-inline d-block d-md-none">
                                        <a class="login-btn text-white">
                                            {% trans "hello" %},  <b class="font-weight-bold text-capitalize">
                                            {{ user.pseudo }}</b>
                                        </a>
                                    </ul>

                                    <div class="login">
                                        <span class="login-btn text-white mr-2">
                                            <span class="login-btn text-white d-none d-md-inline-block">
                                                {% trans "hello" %},
                                                <b class="font-weight-bold text-capitalize">
                                                {{ user.pseudo }}</b>
                                            </span>
                                        </span>

                                        <a href="{% url "accounts:profile" %}" class="login-btn text-white mr-2">
                                            <span class="d-none d-md-inline-block font-weight-bold text-capitalize">
                                                <i class="fa fa-user mr-1"></i>
                                                {% trans "your profile" %}
                                            </span>
                                        </a>

                                        <a href="{% url "panier:detail_panier" %}" class="login-btn text-white font-weight-bold">
                                            <i class="fa fa-shopping-bag mr-1"></i>
                                            {% trans "your orders" %}
                                        </a>
                                    </div>

                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <a href="{% url "accounts:logout" %}" class="text-white font-weight-bold text-capitalize">
                                                <i class="fas fa-sign-out-alt mr-1"></i>
                                                <span class="d-none d-xl-inline-block">
                                                    {% trans "logout" %}
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                {% else %}
                                    <div class="login">
                                        <a href="{% url "accounts:profile" %}" class="login-btn text-white mr-2">
                                            <i class="fa fa-user mr-1"></i>
                                            {% trans "your profile" %}
                                        </a>

                                        <a href="{% url "panier:detail_panier" %}" class="login-btn text-white">
                                            <i class="fa fa-shopping-bag mr-1"></i>
                                            {% trans "your orders" %}
                                        </a>
                                    </div>

                                    <ul class="list-inline">
                                        <a href="{% url "accounts:login" %}" class="login-btn text-white mr-2">
                                            <i class="fas fa-sign-in-alt mr-1"></i>
                                            {% trans "login" %}
                                        </a>

                                        <a href="{% url "accounts:register" %}" class="login-btn text-white">
                                            <i class="fas fa-user-plus mr-1"></i>
                                            {% trans "signup" %}
                                        </a>
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--./topbar-->

            <!-- Navbar -->
            <nav role="navigation" class="sticky-top" id="header">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="container">
                    <div class="row d-flex align-items-center">
                        <div class="col-md-3 text-center text-lg-right my-sm-2">
                            <!-- Navbar brand -->
                            <div class="header-logo">
                                <a href="{% url "shop:all_produit" %}" class="d-block text-uppercase font-weight-bold">{{ site_name }}
                                </a>
                            </div><!-- ./Navbar brand -->
                        </div>

                        <div class="col-md-6">
                            <div class="header-search">
                                <!-- search -->
                                <form role="search" class="position-relative" action="{% url "shop:search" %}">
                                    <div class="input-group">
                                        <input class="input form-control border shadow-none" type="search" placeholder="{% trans "Search for a product or category..." %}" aria-label="search" name="q" autocomplete="false">
                                        <div class="input-group-append shadow-none">
                                            <button class="shadow-none border-0 input-group-text btn-success search-btn text-white" type="submit">{% trans "Search" %}</i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <!-- Links right-->
                        <div class="col-md-3 text-center text-lg-left my-sm-2">
                            <div class="header-ctn">
                                <div>
                                    {% if request.user.is_authenticated %}
                                        <a class="nav-link" href="{% url "panier:detail_panier" %}">
                                            <i class="icon-bag mr-1"></i>
                                            <span>{% trans "Cart" %}</span>
                                            <div class="cart-quantity text-white font-weight-bold">
                                                {% with total_items=panier|length %}
                                                    {% if panier|length > 0  %}
                                                        {{ total_items }}
                                                    {% else %}
                                                        0
                                                    {% endif %}
                                                {% endwith %}
                                            </div>
                                        </a>
                                    {% else %}
                                        <a class="nav-link" href="{% url "panier:detail_panier" %}">
                                            <i class="icon-bag"></i>
                                            <span>{% trans "Cart" %}</span>
                                            </a>
                                    {% endif %}
                                </div>
                            </div><!-- ./Links left-->
                        </div>
                    </div>
                </div>
            </nav>
            <!--/.Navbar-->