ecommerce/urls.py
# -*- coding: utf-8 -*-

"""
    ecommerce URL Configuration
"""

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

admin.autodiscover()

if 'rosetta' in settings.INSTALLED_APPS:
     urlpatterns = i18n_patterns(
          # path('__debug__/', include(debug_toolbar.urls)),
          path(_('admin/'), admin.site.urls),
          path(_('admin/doc/'), include('django.contrib.admindocs.urls')),
          path('', include('accounts.urls', namespace='accounts')),
          path(_('cart/'), include('panier.urls', namespace='panier')),
          path(_('orders/'), include('commandes.urls', namespace='commandes')),
          path(_('payment/'), include('payment.urls', namespace='payment')),
          path(_('coupons/'), include('coupons.urls', namespace='coupons')),
          path('rosetta/', include('rosetta.urls')),
          path('tinymce/', include('tinymce.urls')),
          path('', include('shop.urls', namespace='shop')),
    )

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
# -*- coding: utf-8 -*-


from django.urls import path
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import gettext_lazy as _

from . import views
from marketing.views import email_list_signup
from shop.sitemaps import CatSitemaps


sitemaps = {
    'cat': CatSitemaps,
}

app_name = 'shop'

urlpatterns = (
    # ex: /
    path('', views.all_produit, name='all_produit'),
    # ex: subscribe/
    path(_('subscribe/'), email_list_signup, name='marketing'),

    # ex: search/
    path(_('search/'), views.search, name='search'),

    # ex: shop/product/
    path(_('shop/product/<slug:slug>/<int:id>/'), views.detail_produit, name='detail_produit'),

    # ex: shop/marque/
    path(_('shop/marque/'), views.all_marques, name='all_marque'),
    path(_('shop/marque/<slug:marque_slug>/'), views.liste_marques, name='listing_marques'),

    # ex: shop/category/
    path(_('shop/category/'), views.all_categorie, name='all_categorie'),
    path(_('shop/category/<slug:category_slug>/'), views.liste_categorie, name='listing_categorie'),
    path(_('shop/category/<slug:category_slug>/'), views.all_produit, name='all_produit'),

    # ex: shop/review/
    path(_('shop/review/'), views.review_list, name='review_list'),
    path(_('shop/review/<slug:review_id>/'), views.review_detail, name='review_detail'),
    path(_('shop/add_review/<int:produit_id>/'), views.add_review, name='add_review'),

    # ex: shop/profile/
    path('shop/profile/<slug:username>/', views.user_review_list, name='user_review_list'),
    path('shop/profile/', views.user_review_list, name='user_review_list'),

    # ex: shop/recommendation/ - get wine recommendations for the logged user
    path('shop/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

shop/forms.py
# -*- coding: utf-8 -*-
from django.utils.translation import gettext_lazy as _
from django import forms

from .models import Produit, Review


class ProduitAdminForm(forms.ModelForm):
    class Meta:
        model = Produit
        fields = ['name']

    def clean_price(self):
        cleaned_data = super(ProduitAdminForm, self).clean()
        prix = cleaned_data.get("prix")
        prix_reduit = cleaned_data.get("prix_reduit")

        if prix_reduit > prix:
            raise forms.ValidationError('Erreur le prix marchant ne peut être supérieur au prix réduit')
        return cleaned_data

class ReviewAdminForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'rating', 'comment']

shop/views.py
# -*- coding: utf-8 -*-

import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.db.models import Count, Q
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, redirect, get_object_or_404

# from .recommender import Recommender
from shop.forms import ReviewAdminForm
from shop.setlang import strip_language
from shop.suggestions import update_clusters
from marketing.forms import EmailSubscribeForm
from panier.forms import AjouterProduitPanierForm
from .models import Marque, Categorie, Produit, Pub, Review, Cluster

# Vue pour les recherches sur le site
@require_http_methods(["GET"])
def search(request):
    next_lang = strip_language(request.path)
    categories = Categorie.objects.all()
    produits = Produit.objects.filter(disponible=True)
    try:
        q = request.GET.get('q')
    except:
        q = None

    if q:
        produits = produits.filter(
            Q(name__icontains=q) |
            Q(meta_keywords__icontains=q)
        ).distinct()
    else:
        return redirect('shop:search')

    context = {'query': q, 'produits': produits, 'categories': categories, 'next':next_lang}
    template = 'shop/produit/shop_category_product.html'

    return render(request, template, context)


# Vue pour lister tous les produits
def all_produit(request, category_slug=None):
    next_lang = strip_language(request.path)
    categorie = None
    categories = Categorie.objects.filter()
    produits = Produit.objects.filter(disponible=True).prefetch_related('categorie')

    pub = Pub.objects.all().prefetch_related('categorie')

    form = EmailSubscribeForm()

    if category_slug:
        categorie = get_object_or_404(Categorie, slug=category_slug)
        produits = produits.filter(categorie=categorie)

    context = {'categories': categories,
        'produits': produits, 'form': form, 'pub': pub, 'next': next_lang
    }

    template = 'shop/produit/shop_listing.html'

    return render(request, template, context)


# Vue pour les details des produits
@require_http_methods(["GET"])
def detail_produit(request, id, slug):
    next_lang = strip_language(request.path)
    produit = get_object_or_404(Produit, id=id, slug=slug, disponible=True)
    categories = produit.categorie.all()
    page_title = produit.name
    meta_keywords = produit.meta_keywords
    meta_description = produit.meta_description

    # Similar products
    product_cat_ids = produit.categorie.values_list('id')
    similar_products = Produit.objects.filter(
        categorie__in=product_cat_ids).exclude(id=produit.id).annotate(
        Count("categorie", distinct=True)).prefetch_related('categorie').order_by()[:6]

    #
    form = ReviewAdminForm()
    formulaire_panier_produit = AjouterProduitPanierForm(auto_id='id_%s')

    # r = Recommender()
    # recommended_produits = r.suggest_produits_for([produit], 4)

    template = 'shop/produit/shop_detail.html'
    context = {
        'produit': produit, 'categories':categories,
        'formulaire_panier_produit': formulaire_panier_produit,
        'form': form, 'similar_products': similar_products,
        'page_title' : page_title, 'meta_keywords' : meta_keywords,
        'meta_description' : meta_description, 'next': next_lang
    }

    return render(request, template, context)


# Vue pour lister toutes les categories de produits
def all_categorie(request):
    next_lang = strip_language(request.path)
    page_title = 'categorie'
    categories = Categorie.objects.all()
    produits = Produit.objects.filter(disponible=True).prefetch_related('categorie')

    context = {'categories': categories, 'produits': produits, 'page_title': page_title, 'next': next_lang }
    template = 'shop/produit/shop_category_product.html'

    return render(request, template, context)

# Vue pour lister toutes les marques de produits
def all_marques(request):
    next_lang = strip_language(request.path)
    page_title = 'marques'
    marques = Marque.objects.filter()
    produits = Produit.objects.filter(disponible=True).prefetch_related('marque')

    context = {'marques': marques, 'produits': produits, 'page_title': page_title, 'next': next_lang }
    template = 'shop/produit/shop_category_product.html'

    return render(request, template, context)

# Vue pour lister tous les produits par categorie
def liste_marques(request, marque_slug=None):
    next_lang = strip_language(request.path)
    marque = None
    marques = Marque.objects.filter()
    produits = Produit.objects.filter(disponible=True).prefetch_related('marque')
    if marque_slug:
        marque = get_object_or_404(Marque, slug=marque_slug)
        produits = produits.filter(marque=marque)
        page_title = marque.name

    context = {'marques': marques, 'produits': produits, 'page_title' : page_title, 'next': next_lang}
    template = 'shop/produit/shop_category_product.html'

    return render(request, template, context)

# Vue pour lister tous les produits par categorie
def liste_categorie(request, category_slug=None):
    next_lang = strip_language(request.path)
    categorie = None
    categories = Categorie.objects.all()
    produits = Produit.objects.filter(disponible=True).prefetch_related('categorie')
    if category_slug:
        categorie = get_object_or_404(Categorie, slug=category_slug)
        produits = produits.filter(categorie=categorie)
        page_title = categorie.name
        meta_keywords = categorie.meta_keywords
        meta_description = categorie.meta_description

    context = {'produits': produits, 'page_title': page_title, 'meta_keywords': meta_keywords,
        'meta_description': meta_description, 'next': next_lang}
    template = 'shop/produit/shop_category_product.html'

    return render(request, template, context)


# Review list views
def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date', 'rating')[:9]
    context = {'latest_review_list': latest_review_list}
    template = 'shop/produit/shop_review_list.html'

    return render(request, template, context)

# Review detail views
def review_detail(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    context = { 'review': review }
    template = 'shop/produit/shop_review_detail.html'

    return render(request, template, context)

# add review views
def add_review(request, produit_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    produit = get_object_or_404(Produit, id=produit_id, disponible=True)

    form = ReviewAdminForm()

    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.produit = produit
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        update_clusters()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('shop:detail_produit', args=(produit.id,)))

    template = 'shop/produit/shop_review_detail.html'
    context = { 'produit': produit, 'form': form }

    return render(request, template, context)


def user_review_list(request, username=None):
    if not username:
        username = request.user.username

    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username': username}
    template = 'shop/produit/shop_user_review.html'

    return render(request, template, context)


def user_recommendation_list(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    # get request user reviewd product
    user_reviews = Review.objects.filter(user_name=request.user.username).prefetch_related('produit')
    user_reviews_produit_ids = set(map(lambda x: x.produit.id, user_reviews))

    # get request user cluster name (just the first one righ now)
    try:
        user_cluster_name = User.objects.get(username=request.user.username).cluster.first().name
    except IndexError:
        # if no cluster has been assigned for a user, update clusters
        update_clusters()
        user_cluster_name = User.objects.get(username=request.user.username).cluster.first().name

    # get usernames for other members of the cluster
    user_cluster_other_members = Cluster.objects.get(name=user_cluster_name).users.exclude(username=request.user.username).all()
    other_members_usernames = set(map(lambda x: x.username, user_cluster_other_members))

    # get usernames for other members of the cluster
    other_users_reviews = Review.objects.filter(user_name__in=other_members_usernames).exclude(produit__id__in=user_reviews_produit_ids)
    other_user_reviews_produit_ids = set(map(lambda x: x.produit.id, other_users_reviews))

    # then get a wine list including the previous IDs, order by rating
    produit_list = sorted(list(Produit.objects.filter(id__in=other_user_reviews_produit_ids)),
        key=lambda x: x.average_rating, reverse=True
    )
    print(produit_list)

    context = { 'username': request.user.username, 'produit_list': produit_list }
    template = 'shop/produit/user_recommendation_list.html'

    return render(request, template, context)

shop/templates/shop/produit/shop_category_list.html
{% load i18n static shop_tags humanize %}

<!-- section: recent products list -->
<div class="row">
    {% for cat in categories reversed %}
        <div class="col-3 col-md-6 col-lg-3">
            <figure class="itemside">
                <div class="aside">
                    <div class="img-wrap img-sm rounded-circle blue-gradient">
                        <i class="center-xy fa-2x text-white {% ifchanged cat.name %}
                           {% autoescape off %}{% cycle 'fa fa-car' 'fas fa-shoe-prints' 'fas fa-home' 'fa fa-laptop' 'fa fa-mobile-alt' 'fa fa-book-reader' 'fa fa-tv' 'fa fa-gamepad' %}{% endautoescape %}
                            {% endifchanged %}">
                        </i>
                    </div>
                    <a class="stretched-link" href="{{ cat.get_absolute_url }}"
                        title="{{ cat.get_absolute_url }}">
                    </a>
                </div>
                <figcaption class="text-wrap d-none d-md-inline-block mx-2">
                    <h6 class="title mt-3">
                        {{ cat.name|truncatewords:4 }}
                    </h6>
                    <a class="stretched-link" href="{{ cat.get_absolute_url }}">
                        {% trans "View all category" %}
                    </a>
                </figcaption>
            </figure>
        </div>
    {% endfor %}
</div>

shop/templates/shop/produit/shop_latest_produit.html
                    {% load i18n static shop_tags humanize %}

                    {% for produit in latest_products %}
                        {% include "./tags/shop_list_product.html" %}
                    {% endfor %}

shop/templates/shop/produit/shop_listing.html
{% extends "shop/base.html" %}
{% load i18n static shop_tags humanize %}

{% block carousel %}
    {% include "_includes/carousel.html" %}
{% endblock carousel %}

{% block content %}
    <style type="text/css">
        .card .img-wrap { overflow: hidden; }

        .card-product:hover {
            outline: 1px solid #aaa;
        }

        .card-product:after {
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }

        .card-product .title {
            font-family: sans-serif;
            margin-top: 0;
            font-size: 14px;
            font-weight: 500;
            color: #5b5b5b;
            line-height: 1.4em;
        }

        .card-product .img-wrap {
            position: relative;
            height: 220px;
        }

        .card-product .info-wrap {
            overflow: hidden;
            padding: 10px;
            margin-bottom: 0;
            min-height: 60px;
            border-top: 1px solid #eee;
        }

        .card-product .img-wrap img {
            max-height: 100%;
            max-width: 100%;
            -o-object-fit: cover;
                object-fit: cover;
        }

        /* section: Category itemside */

        .itemside {
            position: relative;
            display: -webkit-inline-box;
            width: 100%;
        }

        .itemside .img-wrap { position: relative; border-radius: 0.25rem 0 0 0.25rem; }
        .itemside img { -o-object-fit: contain; object-fit: contain; }

        .img-sm { -o-object-fit: cover; object-fit: cover; width: 80px; height: 80px; }
        .center-xy {
            top: 50%; left: 50%;
            position: absolute;
            -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }
        .itemside .card-body {
            position: relative;
            z-index: 3;
        }

        .no-gutters > [class*="col-"] { padding-right: 0.25rem !important;
            padding-left: 0.25rem !important;}
    </style>

    <!--section: recent products list -->
    <main class="section-product-list mt-1">
        <div class="container">
            {% if messages %}
                <div class="col-12">
                    {% for message in messages %}
                    <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="card shadow-sm rounded-0">
                <div class="card-header bg-success text-white font-family font-weight-bolder">
                    <div class="float-left">
                        {% trans "New products" %}
                    </div>
                    <div class="text-right">
                        <a class="text-white d-none d-md-inline" href="{% url "shop:all_categorie" as all_categorie %}">
                            {% trans "View more product" %}
                        </a>

                        <a href="{{ all_categorie }}" class="text-white font-weight-bolder">
                            <i class="icon-arrow-right-circle ml-1"></i>
                        </a>
                    </div>
                </div>
                <div class="slick-slider mx-3">
                    <!-- liste des derniers 8 articles -->
                    {% show_latest_products 8 %}
                </div>
            </div>
        </div>
    </main><!--./Section: Products -->

    <!-- section: all category list -->
    <section class="section-cat-list my-2">
        <div class="container">
            <div class="card shadow-none border rounded-0">
                <h5 class="card-header bg-success text-white font-family font-weight-bolder">
                    {% trans "Discover our product categories" %}
                </h5>
                <!-- ./section: liste des categories -->
                <div class="card-body">
                    {% include "shop/produit/shop_category_list.html" %}
                </div>
            </div>
        </div>
    </section><!-- ./section: Category -->

    <!-- section: Publicité -->
    <section class="section-pub my-2">
        <div class="container">
            <div class="card shadow-none border rounded-0">
                <div class="card-body p-1">
                    <div class="row no-gutters">
                        <div class="col-6 col-lg-6">
                            <img class="img-fluid" src="{% static "img/banners/slide2.jpg" %}">
                        </div>

                        <div class="col-6 col-lg-6">
                            <img class="img-fluid" src="{% static "img/banners/slide1.jpg" %}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- ./section: Publicité -->


    <!-- section: smartphone -->
    <section class="section-pub my-2">
        <div class="container">
            <div class="card shadow-none border">
                <div class="card-header blue-gradient d-flex justify-content-between">
                    <div>
                        <span class="text-white font-weight-bolder">
                            {% trans "Best deals smartphone" %}
                        </span>
                    </div>

                    <div>
                        <a class="text-white font-weight-bolder d-none d-md-inline" href="{{ all_categorie }}">
                            {% trans "View more smartphone product" %}
                        </a>

                        <a href="{{ all_categorie }}" class="text-white font-weight-bolder">
                            <i class="icon-arrow-right-circle ml-1"></i>
                        </a>
                    </div>
                </div>

                {% include "./tags/shop_product.html" %}
            </div>
        </div>
    </section><!-- ./section: smartphone -->

    <section class="section-pub my-2">
        <div class="container">
            <div class="card shadow-none border rounded-0">
                <h5 class="card-header peach-gradient text-white font-family font-weight-bolder">
                    {% trans "Best deals TV &amp; audio" %}
                </h5>
                {% include "./tags/shop_product.html" %}
            </div>
        </div>
    </section>

    {% if user.is_authenticated %}
        <section class="section-pub my-2">
            <div class="container">
                <div class="card shadow-none border rounded-0">
                    <h5 class="card-header bg-white text-black font-family">
                        {% trans "Recently viewed articles" %}
                    </h5>
                    {% include "./tags/shop_product.html" %}
                </div>
            </div>
        </section>
    {% endif %}
{% endblock content %}

shop/templates/shop/produit/shop_review_add.html
{% load i18n static shop_tags humanize %}
<div class="col-6">
    {% if user.is_authenticated %}
        <form action="{% url 'shop:add_review' produit.id %}" method="post">
            <h3 class=" text-justify text-monospace">
            Add your review</h3>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% csrf_token %}
            <div class="d-inline-flex mb-3">
                <div class="col">
                    {{ form.rating }}
                    {{ form.rating.errors }}
                </div>

                <div class="col col-lg-12">
                    <input type="text" name="{{ form.user_name.name }}" class="form-control shadow-none" id="{{ form.user_name.id_for_label }}" placeholder="{{ form.user_name.label }}*">
                </div>
            </div>

            <div class="col-12">
                <textarea name="{{ form.comment.name }}" class="form-control form-control-sm shadow-none" id="{{ form.comment.id_for_label }}" cols="10" rows="10" placeholder="Laisser votre avis sur le produit ..."></textarea>

                {{ form.honeypot }}{{ form.content_type }}{{ form.object_pk }}{{ form.timestamp }}{{ form.security_hash }}
            </div>

            <div class="col-12 text-center">
                <input class="btn btn-sm btn-success shadow-none" type="submit" name="" value="add">
            </div>
        </form>

        <li class="list-unstyled">
            <a href="{% url 'shop:user_recommendation_list' %}">
            product suggestions</a>
        </li>
    {% endif %}
</div>

shop/templates/shop/produit/shop_review_detail.html
{% load static %}

<h2><a href="">{{ review.produit.name }}</a></h2>

<h4>
    Rated {{ review.rating }} of 5 by <a href="{% url 'shop:user_review_list' review.user_name %}">
    {{ review.user_name }}</a>
</h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>

shop/templates/shop/produit/shop_review_list.html
{% load i18n static shop_tags humanize %}

<h2>Latest reviews</h2>

{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4>
            <a href="{% url 'shop:review_detail' review.id %}">{{ review.produit.name }}</a>
        </h4>

        <h4>
            Rated {{ review.rating }} of 5 by
            <a>{{ review.user_name }}</a>
        </h4>
        <p>{{ review.pub_date }}</p>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}

shop/templates/shop/produit/shop_similar_product.html
            {% load i18n static shop_tags humanize %}
            <style type="text/css">
                .badge-new, .badge-sale {
                    position: absolute;
                    top: 0.25rem; z-index: 10;
                    width: 60px; height: 25px;
                    margin-top: 0.25rem;
                    background-color: #cf5050;
                    color: #efefef; font-size: 16px; font-weight: 500;
                }

                .badge-sale {
                    background-color: #cf5055;
                }

                .l-container .l-container-img >:first-child {
                    position: relative; display: block;
                }

                .l-container:hover {
                    outline: 1px solid #aaa;
                    -moz-outline-radius: 5px;
                }

                .l-container .l-container-img .l-container-tags {
                    top: 0; right: 0; vertical-align: inherit; border-width: 0; direction: rtl;
                }
                .l-container .l-container-img .l-container-tags > .l-container-label-tags {
                    margin: 1px 0 0 0; opacity: .92; direction: ltr;
                }
            </style>
            <!--Grid row produit recommandé -->
            <div class="row justify-content-center">
                {% for produit in similar_products %}
                    <div class="col-3 col-sm-4 l-container my-2">
                        <div class="l-container-product p-2">
                            <div class="l-container-img position-relative overflow-hidden text-center">
                                <a href="{{ produit.get_absolute_url }}" class="{{ produit.get_absolute_url }}">
                                    <img src="{% if produit.image %}{{ produit.image.url }} {% else %} {% static "img/noimage.png" %}{% endif %}" alt="{{ produit.name }}"
                                    class="card-img-top img-fluid">
                                    <a href="{{ produit.get_absolute_url }}" class="stretched-link"></a>
                                </a>

                                <a href="{{ produit.get_absolute_url }}" class="text-dark small font-weight-normal">
                                    {{ produit.name| safe |truncatewords:6 }}
                                </a>
                                <span class="text-uppercase small d-inline-block">
                                    {{ produit.prix_reduit | floatformat:0 | upper }} fcfa
                                    <del class="text-muted small ml-1">
                                        {{ produit.prix | floatformat:0 | upper }} fcfa
                                    </del>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

shop/templates/shop/produit/shop_user_review.html
<h2>Reviews by {{ username }}</h2>

shop/templates/shop/produit/user_recommendation_list.html
<h2>Product recommendation for {{ username }}</h2>

{% for produit_list in produit_list %}
    {{ produit_list.name }}
{% endfor %}