commandes/urls.py
# -*- coding: utf-8 -*-
"""
    commandes URL Configuration
"""
from django.utils.translation import gettext_lazy as _
from django.urls import path
from . import views as commande

app_name = 'commandes'

urlpatterns = [
    path(_('create/'), commande.creer_commande, name="commander"),
    path(_('admin/commande/<int:id_commande>/'), commande.detail_commande_admin,
         name='detail_commande_admin'),
    path(_('admin/commande/<int:id_commande>/pdf/'), commande.pdf_commande_admin,
         name='pdf_commande_admin'),
]

coupons/urls.py
from django.utils.translation import gettext_lazy as _
from django.urls import path
from . import views

app_name = 'coupons'
urlpatterns = [
    path(_('coupon/appliquer/'), views.utiliser_le_coupon, name='appliquer_le_coupon'),
]

ecommerce/urls.py
# -*- coding: utf-8 -*-

"""
    ecommerce URL Configuration
"""

from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

admin.autodiscover()

if 'rosetta' in settings.INSTALLED_APPS:
     urlpatterns = i18n_patterns(
          # path('__debug__/', include(debug_toolbar.urls)),
          path(_('admin/'), admin.site.urls),
          path(_('admin/doc/'), include('django.contrib.admindocs.urls')),
          path('', include('accounts.urls', namespace='accounts')),
          path(_('cart/'), include('panier.urls', namespace='panier')),
          path(_('orders/'), include('commandes.urls', namespace='commandes')),
          path(_('payment/'), include('payment.urls', namespace='payment')),
          path(_('coupons/'), include('coupons.urls', namespace='coupons')),
          path('rosetta/', include('rosetta.urls')),
          path('tinymce/', include('tinymce.urls')),
          path('', include('shop.urls', namespace='shop')),
    )

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panier/urls.py
# -*- coding: utf-8 -*-

"""
    Panier URL configuration
"""

from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views as views

app_name = 'panier'

urlpatterns = [
    path('', views.detail_panier, name="detail_panier"),
    path(_('panier/add/<int:id_produit>/'), views.ajout_panier, name="ajout_panier"),
    path(_('panier/remove/<int:id_produit>/'), views.enlever_panier, name="enlever_panier"),
]

shop/urls.py
# -*- coding: utf-8 -*-


from django.urls import path
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import gettext_lazy as _

from . import views
from marketing.views import email_list_signup
from shop.sitemaps import CatSitemaps


sitemaps = {
    'cat': CatSitemaps,
}

app_name = 'shop'

urlpatterns = (
    # ex: /
    path('', views.all_produit, name='all_produit'),
    # ex: subscribe/
    path(_('subscribe/'), email_list_signup, name='marketing'),

    # ex: search/
    path(_('search/'), views.search, name='search'),

    # ex: shop/product/
    path(_('shop/product/<slug:slug>/<int:id>/'), views.detail_produit, name='detail_produit'),

    # ex: shop/marque/
    path(_('shop/marque/'), views.all_marques, name='all_marque'),
    path(_('shop/marque/<slug:marque_slug>/'), views.liste_marques, name='listing_marques'),

    # ex: shop/category/
    path(_('shop/category/'), views.all_categorie, name='all_categorie'),
    path(_('shop/category/<slug:category_slug>/'), views.liste_categorie, name='listing_categorie'),
    path(_('shop/category/<slug:category_slug>/'), views.all_produit, name='all_produit'),

    # ex: shop/review/
    path(_('shop/review/'), views.review_list, name='review_list'),
    path(_('shop/review/<slug:review_id>/'), views.review_detail, name='review_detail'),
    path(_('shop/add_review/<int:produit_id>/'), views.add_review, name='add_review'),

    # ex: shop/profile/
    path('shop/profile/<slug:username>/', views.user_review_list, name='user_review_list'),
    path('shop/profile/', views.user_review_list, name='user_review_list'),

    # ex: shop/recommendation/ - get wine recommendations for the logged user
    path('shop/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)

panier/models.py
from django.db import models

# Create your models here.

panier/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

CHOIX_QUANTITE_PRODUITS = [(i, str(i)) for i in range(1, 11)]


# Formulaire d'ajout de produit au panier
class AjouterProduitPanierForm(forms.Form):
    quantite = forms.TypedChoiceField(error_messages={'required': _('Please enter a number')},
        choices=CHOIX_QUANTITE_PRODUITS, coerce=int, label=_('Quantity'))

    update = forms.BooleanField(required=False, initial=False,
        widget=forms.HiddenInput)

    # Modification de l'affichage des variables
    quantite.widget.attrs.update({'class': 'custom-select custom-select-sm shadow-none border-0'})

panier/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Produit
from .panier import Panier
from .forms import AjouterProduitPanierForm
from coupons.forms import CouponForm
from shop.setlang import strip_language


# Create your views here.

@require_POST
def ajout_panier(request, id_produit):
    panier = Panier(request)
    produit = get_object_or_404(Produit, id=id_produit)
    formulaire = AjouterProduitPanierForm(request.POST)
    if formulaire.is_valid():
        cd = formulaire.cleaned_data
        panier.ajout(produit=produit, quantite=cd['quantite'],
            update_quantite=cd['update'])
    return redirect('panier:detail_panier')


def enlever_panier(request, id_produit):
    panier = Panier(request)
    produit = get_object_or_404(Produit, id=id_produit)
    panier.enlever(produit)
    return redirect('panier:detail_panier')

def detail_panier(request):
    panier = Panier(request)
    next_lang = strip_language(request.path)
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    for item in panier:
        item['form_update_quantite'] = AjouterProduitPanierForm(initial={'quantite': item['quantite'], 'update': True})

    # On ajout le coupon au panier
    appliquer_le_coupon = CouponForm()

    context = {'panier': panier, 'appliquer_le_coupon': appliquer_le_coupon, 'next': next_lang}
    template = 'panier/panier_detail.html'

    return render(request, template, context)

panier/templates/panier/panier_detail.html
{% extends "shop/base.html" %}
{% load i18n static shop_tags humanize %}

{% block content %}
    <!--Main layout-->
    <style type="text/css">
        .empty-cart .empty-cart-content i {
            height: 165px; width: 165px; border-radius: 50%;
            border: 1px solid #d0d0d0; font-size: 72px; line-height: 150px;
        }

        .empty-cart .empty-cart-content h3 {
            font-size: 24px; color: #0b1033; font-weight: 600;
            letter-spacing: .60px; padding: 30px 0px 15px 0px;
        }

        .empty-cart .empty-cart-content h4 {
            font-size: 14px; color: #666;
        }
    </style>
    <main class="mt-1 pb-5">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Grid column -->
                {% if panier %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-10 p-3 bg-white rounded shadow-none mb-auto">
                                <!-- .shopping cart table-->
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class="border-bottom">
                                            <tr>
                                                <th class="border-0" scope="col">
                                                    <div class="p-2 px-3 text-uppercase font-weight-bolder">{% trans "Product" %}</div>
                                                </th>

                                                <th class="border-0" scope="col">
                                                    <div class="py-2 text-uppercase font-weight-bolder">{% trans "Quantity" %}</div>
                                                </th>

                                                <th class="border-0" scope="col">
                                                    <div class="py-2 text-uppercase font-weight-bolder">{% trans "Price" %}</div>
                                                </th>

                                                <th class="border-0" scope="col">
                                                    <div class="py-2 text-uppercase font-weight-bolder">
                                                        {% trans "Sub total" %}
                                                    </div>
                                                </th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            {% for element in panier %}
                                                {% with produit=element.produit %}
                                                    <tr class="{% if forloop.first %}border-bottom{% endif %}">
                                                        <th scope="row">
                                                            <div class="p-1">
                                                                <img src="{% if produit.image %}{{ produit.image.url }} {% else %}{% static "img/cart.png" %}{% endif %}" alt="{{ produit.name}}" width="70" class="img-fluid rounded shadow-none">
                                                                <div class="ml-2 d-inline-block align-middle">
                                                                    <h5 class="mb-0 my-2">
                                                                        <a href="{{ produit.get_absolute_url }}" class="text-dark d-inline-block align-middle h6">
                                                                            {{ produit.name | truncatewords:10 }}
                                                                        </a>
                                                                    </h5>

                                                                    <span class="font-weight-bold text-uppercase small d-block mt-1">
                                                                        <a href="{% url "panier:enlever_panier" produit.id %}" class="text-danger">
                                                                            <i class="fa fa-trash mr-1"></i>
                                                                            {% trans "delete" %}
                                                                        </a>

                                                                        <a href="#" class="ml-3 text-danger">
                                                                            <i class="icon-heart"></i>
                                                                            {% trans "add to favorite" %}
                                                                        </a>
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        </th>
                                                        <td class="align-middle">
                                                            <form action="{% url "panier:ajout_panier" produit.id %}" class="form-inline" method="post">
                                                                {{ element.form_update_quantite.quantite }}
                                                                {{ element.form_update_quantite.update }}
                                                                {% csrf_token %}
                                                                <button type="submit" class="btn btn-sm p-0 shadow-none">
                                                                    <span class="icon-refresh text-success font-weight-bolder h6" aria-hidden="true"></span>
                                                                </button>
                                                            </form>
                                                        </td>
                                                        <td class="align-middle">
                                                            <strong>{{ produit.prix|floatformat:"0" }}
                                                            </strong>
                                                        </td>
                                                        <td class="align-middle font-weight-bold text-success text-uppercase">
                                                            {% if element.prix_total %}
                                                                {{ element.prix_total|floatformat:"0" }} frcfa
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                {% endwith %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div> <!-- ./shopping cart table-->
                            </div>
                        </div>

                        <div class="row py-5 p-4 justify-content-center bg-white rounded shadow-none">
                            <div class="col-lg-5">
                                <div class="bg-light rounded-pill px-4 py-2 text-uppercase font-weight-bold">
                                    {% trans "coupon code" %}
                                </div>
                                <div class="p-3">
                                    <p class="font-italic mb-4">
                                    {% trans "If you have a coupon code, please enter it in the box below" %}</p>

                                    <form action="{% url "coupons:appliquer_le_coupon" %}" method="post">
                                        <div class="md-form input-group input-group-sm mb-4 border rounded-pill">
                                            {{ formulaire.errors }}
                                            {{ appliquer_le_coupon.code }}
                                            <div class="input-group-append border-0">
                                                {% csrf_token %}
                                                <button id="btnCoupon" class="input-group-text btn btn-success px-3 rounded-pill shadow-none">
                                                    <i class="fa fa-gift mr-2"></i>{% trans "Apply coupon" %}
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="bg-light rounded-pill px-4 py-2 text-uppercase font-weight-bold">
                                    {% trans "Instruction for seller" %}
                                </div>
                                <div class="p-3">
                                    <p class="font-italic mb-4">{% trans "If you have some informattion for the seller you can leave theme in the box below" %}</p>
                                    <textarea name="" cols="30" rows="2" class="form-control shadow-none"></textarea>
                                </div>
                            </div>

                            <div class="col-lg-5">
                                <div class="bg-light rounded-pill px-4 py-2 text-uppercase font-weight-bold">
                                {% trans "Order sommary" %}</div>
                                <div class="p-3">
                                    <p class="font-italic mb-3">{% trans "Shipping and additionnal costs are calculated based on values you have entered." %}</p>
                                    <ul class="list-unstyled mb-4">
                                        <li class="d-flex justify-content-between py-3 border-bottom">
                                            <strong class="text-muted">{% trans "Sub total" %}</strong>
                                            <strong class="text-uppercase">
                                            {{ panier.get_cout_total|floatformat:0 }}</strong>
                                        </li>

                                        {% if panier.coupon.discount %}
                                            <li class="d-flex justify-content-between py-3 border-bottom">
                                                <strong class="text-muted">{% trans "Discount" %}</strong>
                                                <strong>{{ panier.coupon.discount|floatformat:0 }}%</strong>
                                            </li>

                                            <li class="d-flex justify-content-between py-3 border-bottom">
                                                <strong class="text-muted">{% trans "Discount cout" %}</strong>
                                                <strong class="text-uppercase">-{{ panier.get_discount|floatformat:0 }}</strong>
                                            </li>
                                        {% endif %}

                                        {% if panier.get_cout_total_apres_discount %}
                                            <li class="d-flex justify-content-between py-2 border-bottom text-uppercase font-weight-bold">
                                                <strong>{% trans "Total" %}</strong>
                                                <h5 class="font-weight-bold text-uppercase text-danger">
                                                {{ panier.get_cout_total_apres_discount|floatformat:0|safe }} frcfa</h5>
                                            </li>
                                        {% endif %}
                                    </ul>

                                    <div class="d-flex justify-content-between">
                                        <div><a type="submit" href="{% url "shop:all_categorie" %}" class="btn btn-md btn-light bg-white rounded-pill py-2 shadow-none">
                                        {% trans "Continue shopping" %}</a></div>

                                        <div><a type="submit" href="{% url "commandes:commander" %}" class="btn btn-md btn-success rounded-pill py-2 shadow-none">
                                        {% trans "Procced to checkout" %}</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <section class="text-center p-5 empty-cart">
                        <div class="container">
                            <div class="empty-cart-content">
                                <i class="icon-handbag icons d-inline-block"></i>
                                <h3 class="font-weight-bold">{% trans "Your cart is empty" %} !</h3>
                                <h4>{% trans "Return" %}
                                    <a href="{% url "shop:all_categorie" %}" class="font-weight-normal">{% trans "shopping cart" %}</a>
                                </h4>
                            </div>
                        </div>
                    </section>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock content %}